RecipeFormatVersion: '2020-01-25'

ComponentName: com.example.HelloWorld
ComponentVersion: '1.0.3'

ComponentDescription: Hello World NodeJS component
ComponentPublisher: Dega

ComponentDependencies:
  aws.greengrass.Cli:
    VersionRequirement: ">=2.0.0"
    DependencyType: HARD

Manifests:
  - Platform:
      os: linux

    Artifacts:
      - URI: s3://greengrass-artifact-dega-test/com.example.HelloWorld/1.0.3/index.js

    Lifecycle:
      Run: |
        /usr/bin/node {artifacts:path}/index.js

    ComponentConfiguration:
      DefaultConfiguration:
        accessControl:
          aws.greengrass.ipc.mqttproxy:
            com.example.HelloWorld:mqtt:
              policyDescription: "Allow publish to IoT Core via IPC"
              operations:
                - aws.greengrass#PublishToIoTCore
              resources:
                - "edge/telemetry"