RecipeFormatVersion: '2020-01-25'

ComponentName: com.example.HelloWorld
ComponentVersion: '1.0.0'

ComponentDescription: Hello World NodeJS component
ComponentPublisher: Dega

Manifests:
  - Platform:
      os: linux

    Artifacts:
      - URI: s3://greengrass-artifact-dega-test/com.example.HelloWorld/1.0.0/index.js

    Lifecycle:
      Run: |
        /usr/bin/node {artifacts:path}/index.js