RecipeFormatVersion: '2020-01-25'

ComponentName: com.example.HelloWorld
ComponentVersion: '1.0.0'

ComponentDescription: Greengrass resilient data ingestion with persisted queue on disk and buffering
ComponentPublisher: Dega

ComponentDependencies:
  aws.greengrass.Cli:
    VersionRequirement: ">=2.0.0"
    DependencyType: HARD


Manifests:
  - Platform:
      os: linux

    Artifacts:
      - URI: s3://greengrass-artifact-dega-test/com.streammanager/1.0.0/stream-mgr.zip
        Unarchive: ZIP

    Lifecycle:
      Run: |
        cd {artifacts:decompressedPath}/stream-mgr
        /usr/bin/node index.js