RecipeFormatVersion: '2020-01-25'

ComponentName: com.dataingestion
ComponentVersion: '1.0.14'

ComponentDescription: Greengrass resilient data ingestion with persisted queue on disk and buffering
ComponentPublisher: Dega

ComponentDependencies:
  aws.greengrass.Cli:
    VersionRequirement: ">=2.0.0"
    DependencyType: HARD

  aws.greengrass.StreamManager:
    VersionRequirement: ">=2.0.0"
    DependencyType: HARD

ComponentConfiguration:
  DefaultConfiguration:
    accessControl:
      aws.greengrass.streammanager:
        com.dataingestion.bridge:
          policyDescription: "Allow Stream Manager access"
          operations:
            - aws.greengrass#PutMessage
            - aws.greengrass#ListStreams
            - aws.greengrass#DescribeStream
            - aws.greengrass#ReadMessages
          resources:
            - "*"

Manifests:
  - Platform:
      os: linux

    Artifacts:
      - URI: s3://greengrass-artifact-dega-test/com.dataingestion/1.0.14/stream-mgr.zip
        Unarchive: ZIP

    Lifecycle:
      Run: |
        set -e
        cd {artifacts:decompressedPath}/stream-mgr
        exec /usr/bin/node index.js